import React from "react";

const CheckBoxJSON = [
    { "Name" : "Accessibility", "Box" : false},
    { "Name" : "Animals", "Box" : false},
    { "Name" : "Biomedical", "Box" : false},
    { "Name" : "Business and Economics", "Box" : false},
    { "Name" : "Children", "Box" : false},
    { "Name" : "Climate Change", "Box" : false},
    { "Name" : "Community Engagement", "Box" : false},
    { "Name" : "Computing", "Box" : false},
    { "Name" : "Culture and Language", "Box" : false},
    { "Name" : "Education","Box" : false },
    { "Name" : "Emerging Technologies", "Box" : false},
    { "Name" : "Energy", "Box" : false},
    { "Name" : "Environmental Management", "Box" : false},
    { "Name" : "Food", "Box" : false},
    { "Name" : "Health and Wellbeing", "Box" : false},
    { "Name" : "History", "Box" : false},
    { "Name" : "Industry and Manufacturing", "Box" : false},
    { "Name" : "Infrastructure/Buildings","Box" : false},
    { "Name" : "Innovation and Entrepreneurship", "Box" : false},
    { "Name" : "Interactive Media", "Box" : false},
    { "Name" : "International Relations", "Box" : false },
    { "Name" : "Libraries and Archives", "Box" : false},
    { "Name" : "Materials", "Box" : false },
    { "Name" : "Museum", "Box" : false },
    { "Name" : "Natural Resources", "Box" : false },
    { "Name" : "Organizational Management", "Box" : false },
    { "Name" : "Policy", "Box" : false },
    { "Name" : "Politics", "Box" : false },
    { "Name" : "Public Engagement", "Box" : false },
    { "Name" : "Public Services", "Box" : false },
    { "Name" : "Recreation", "Box" : false },
    { "Name" : "Rural Development", "Box" : false },
    { "Name" : "Security", "Box" : false },
    { "Name" : "Social Justice", "Box" : false },
    { "Name" : "Space", "Box" : false },
    { "Name" : "Sustainable Development", "Box" : false },
    { "Name" : "Techniques", "Box" : false },
    { "Name" : "Tourism", "Box" : false },
    { "Name" : "Transportation", "Box" : false },
    { "Name" : "Urban Plannings", "Box" : false },
    { "Name" : "Water", "Box" : false },
    { "Name" : "Women", "Box" : false },
]

export default CheckBoxJSON;
